# Generated by Django 5.2.1 on 2025-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_invoice_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
